# Generated by Django 4.2.3 on 2023-09-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person_a',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('introduction', models.TextField(verbose_name='介绍')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='static/images_people/', verbose_name='图片')),
            ],
        ),
        migrations.CreateModel(
            name='Person_b',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('introduction', models.TextField(verbose_name='介绍')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='static/images_people/', verbose_name='图片')),
            ],
        ),
    ]
