# Generated by Django 4.2.3 on 2023-09-02 12:23

from django.db import migrations, models
import navi.models


class Migration(migrations.Migration):

    dependencies = [
        ('navi', '0003_course_model_delete_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_model',
            name='notes',
            field=models.FileField(upload_to='static/notes/', validators=[navi.models.validate_html_extension]),
        ),
    ]
